name: Get Latest Release Info

on:
  workflow_dispatch:

jobs:
  get-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest release
      id: latest-release
      uses: actions/github-script@v7
      with:
        script: |
          const release = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          return release.data;

    - name: Print release version
      run: |
        echo "The latest release version is ${{ steps.latest-release.outputs.tag_name }}"
