name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate version
      run: |
        echo "Validating version ${{ github.event.release.tag_name }}"
      if: github.event_name == 'release'

    - name: Trigger Docker build workflow
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'docker-image.yml',
            ref: github.event.release.tag_name,
          })
